const achievements = [
	{name:'Ding!', objective:'Reach Level 10'},
	{name:'Demon Hunter', objective:'Reach Level 30'},
	{name:'V for Vran', objective:'Reach Level 50'},
	{name:'Show-off', objective:'Make 2500 kills with 5 active Hexes'},
	{name:'Serious Vran', objective:'Make 15000 kills with 5 active Hexes'},
	{name:'Tactical Vran', objective:'Kill 25 enemies with a single attack'},
	{name:'De&shy;mo&shy;nom&shy;i&shy;con', objective:'Kill 50 enemies with a single demon power'},
	{name:'Abstinence Kills', objective:'Kill 500 enemies without using consumables'},
	{name:'Slashing Pump&shy;kins', objective:'Destroy 100 pumpkins'},
	{name:'The Five Trials', objective:'Complete 5 normal challenges on a single map in Zagoravia'},
	{name:'Hard to Chal&shy;lenge', objective:'Complete all normal challenges in 20 different locations in Zagoravia'},
	{name:'Tenacious V', objective:'Complete all normal challenges in Zagoravia'},
	{name:'New Hori&shy;zons', objective:'Complete an elite challenge in Zagoravia'},
	{name:'Been There, Done That', objective:'Complete all elite challenges in Zagoravia'},
	{name:'The Curious Hunter', objective:'Find all secrets in the Hunting Grounds'},
	{name:'No Rock Un&shy;turn&shy;ed', objective:'Find all secrets in 20 different locations in Zagoravia'},
	{name:'Know-it-All', objective:'Find all secrets in Zagoravia'},
	{name:'Leg&shy;endary', objective:'Equip a Legendary weapon'},
	{name:'Master Crafter', objective:'Transmute a perfect weapon', notes:['Completely upagrade any weapon.','While the item is in the transmutation machine, all bars on the left must be filled.']},
	{name:'Ex&shy;plod&shy;ing Chick&shy;ens', objective:'Shoot 250 chickens', notes:['Can only be achieved with the <weapon rarity="legendary">Chicken Cannon</weapon>.','Once you found it, shoot it at least 84 times.']},
	{name:'Dances With Skele&shy;tons', objective:'Dance with the skeletons'},
	{name:'We are the Cham&shy;pi&shy;ons!', objective:'Defeat 25 Champions or Tyrants'},
	{name:'Utilizer', objective:'Have 100 monsters being killed by their peers'},
	{name:'Magellan Vran', objective:'Set foot in every area in Zagoravia'},
	{name:'Victor Vain', objective:'Have 6 outfits'},
	{name:'Fool Proof', objective:'Collect all the Fool Destiny Cards', notes:['There is only one <card>The Fool</card> but it can come with 10 different jokes.','Find or buy all 10 variants.']},
	{name:'Zagore Hold\'em', objective:'Collect 25 different Destiny Cards'},
	{name:'Tzar Bomba', objective:'Inflict 2500 damage with a single hit'},
	{name:'Steady Hand Vic', objective:'Have 25 consecutive split-timed attacks'},
	{name:'Slash and Slash', objective:'Make 5 Slash attacks in 3 seconds'},
	{name:'Gun&shy;slinger', objective:'Make 10 Aimed Shots in 3 seconds'},
	{name:'Bonetti\'s Of&shy;fense', objective:'Charge 4 times within 8 seconds'},
	{name:'Bal&shy;lis&shy;tic Vic', objective:'Hit enemies with 10 consecutive Mortar attacks'},
	{name:'Holier than Thou', objective:'Have 6 equipped Divine cards', notes:['When you reach level 55 you have enough card slots to equip 6 cards.']},
	{name:'In It For The Gold', objective:'Acquire 150 000 pieces of Gold'},
	{name:'Steamed Up', objective:'Trade with GebaN'},
	{name:'De-chrom&shy;er', objective:'Slay the Chromatic Essence', notes:['You get this achievement for beating the boss at the end of <location>The Devil\'s Throat</location>']},
	{name:'The Si&shy;lencer', objective:'Slay the Screeching Calamity', notes:['Slay the boss in <location>Defiled Chapel</location>']},
	{name:'Cruel Giant', objective:'Step on 10 Mites within 5 seconds'},
	{name:'Tough Nut', objective:'Reach 250 Armor'},

	{name:'Lord Gabriel', objective:'Defeat Lord Gabriel', secret:true},
	{name:'The Blood&shy;suck&shy;er', objective:'Defeat Lord Gabriel on Hard Mode', secret:true},
	{name:'The Elder One', objective:'Defeat Lord Gabriel with a character who never died', secret:true},
	{name:'The Host', objective:'Defeat Rachnoss the Host', secret:true},
	{name:'The Brood&shy;moth&shy;er', objective:'Defeat Mordra the Broodmother', secret:true},
	{name:'The Im&shy;mor&shy;tal', objective:'Defeat Vail the Immortal', secret:true},
	{name:'The Fall&shy;en', objective:'Defeat Adrian The Fallen', secret:true},
	{name:'The So&shy;lic&shy;i&shy;tor', objective:'Defeat Wa-Lee the Solicitor', secret:true},
	{name:'Apoc&shy;a&shy;lypse', objective:'Defeat Apocalypse', secret:true},
	{name:'Four&shy;some', objective:'Defeat Adrian The Fallen with a party of 4 in Multiplayer', secret:true},
	
	{name:'Accidentally on Purpose', objective:'Complete 5 Challenges in a randomly generated dungeon'},
	{name:'An&shy;gel, Vam&shy;pire Slay&shy;er', objective:'Transmute a Relic'},
	{name:'Applied Phlebotinum', objective:'Transmute an Apparatus'},
	{name:'Back of Beyond', objective:'Complete the Fractured Worlds story'},
	{name:'Best of Both Worlds', objective:'Transform 3 Mites into dancing skeletons'},
	{name:'Calculated Risk', objective:'Transmute a Phoenix'},
	{name:'Crying Shame', objective:'Interrupt a singing Succubus with Crying Shame'},
	{name:'Eat the Rich', objective:'Defeat the Queen of the Damned'},
	{name:'End of Time', objective:'Complete the Motörhead story'},
	{name:'Fit as a Fiddle', objective:'Reach Level 60'},
	{name:'Gatecrasher', objective:'Play 5 days in Cadaver City'},
	{name:'Glory Hog', objective:'Complete 100 Challenges in a randomly generated dungeon'},
	{name:'Heartbreaker', objective:'Have a network of 6 Heartbreakers on the ground'},
	{name:'Hellraiser', objective:'Complete all Monuments of Rock'},
	{name:'In The Dark', objective:'Reach Tier 50 in the Fracture'},
	{name:'Impossibly Cool', objective:'Transmute a perfect Talisman'},
	{name:'Juggling Frogs', objective:'Complete 50 Challenges in a randomly generated dungeon'},
	{name:'King of Kings', objective:'Kill 250 headbanging monsters with a lightning strike'},
	{name:'Last Straw', objective:'Complete the Fractured Worlds story on Hardcore Hard Mode'},
	{name:'Live To Win', objective:'Complete all Elite Challenges in the Motörhead World'},
	{name:'Lost Johnny', objective:'Discover all Secrets in the Motörhead World'},
	{name:'Method to Mad&shy;ness', objective:'Reach Tier 50 in The Fracture on Hardcore Hard Mode'},
	{name:'Older Is Better', objective:'Transmute an Artifact'},
	{name:'On Parole', objective:'Equip Legendary Revolvers, The Gunslinger and The Silver Bullet'},
	{name:'One Track Mind', objective:'Collect 18 different weapon enhancing destiny cards'},
	{name:'One Short Life', objective:'Complete the Motörhead story on Hardcore Hard Mode'},
	{name:'Oooh Shiny', objective:'Equip a Talisman'},
	{name:'Or&shy;gas&shy;ma&shy;tron', objective:'Defeat Orgasmatron'},
	{name:'Rock It', objective:'Have 50 monsters headbanging at the same time'},
	{name:'Run, Forest, Run', objective:'Play 5 days in Amaranthine Autumn'},
	{name:'Speed&shy;freak', objective:'Deliver 6 critical hits with a single Bullet Hell attack'},
	{name:'Spelunker', objective:'Play 5 days in The Lethean Caves'},
	{name:'Stand', objective:'Use the Swarm\'s projectiles to kill 6 enemies at the same time'},
	{name:'Sunny Smile', objective:'Play 5 days in the Hanging Gardens of Ea'},
	{name:'Sweet Revenge', objective:'Inflict Crippled, Bleeding, Weakness, Headbang and Electrocuted to a single enemy'},
	{name:'Tell Me Who To Kill', objective:'Complete all Normal Challenges in the Motörhead World'},
	{name:'Thunder And Light&shy;ning', objective:'Equip Legendary Guitar, The Muse and The Bard'},
	{name:'Warpig Machine', objective:'Defeat the Warpig Machine'},
	{name:'We Are Mot&ouml;r&shy;head', objective:'Complete the Motörhead Band Members collection'},
	{name:'What Museum?', objective:'Transmute an Antique'},
];