const locations = [
	{name:'Castle Zagore',notes:['The hub of this world.','Home of <npc>Queen Katarina</npc> and her military advisor <npc>Sir Krum</npc>','Traders: <npc>Damian</npc> the Alchemist and <npc>Patriarch Casimir</npc>','<npc>Irene</npc> and <npc>Private Stash</npc> will join, once you meet them during the main quest.'],noimage:true},
	{name:'The Royal Gardens',links:['Befouled Tomb','Sepulcher of the Damned','Den of the Broodmother','The Royal Crypt'],secrets:3,
		normal:['Use 10 Demon powers','Slay 25 Spider Eggs','Slay all 5 Spider Nests in the Labyrinth','Slay Argus the Dreaded Mage','Slay the Chessmaster'],
		elite:['Slay 10 Wraiths with 5 Active <hex>Hexes</hex>','Slay 80 Monsters with Melee Attacks while above 80% helath','Slay 2 Champions Affected by <effect>Cripple</effect>','Slay 80 Monsters without taking damage and without using Demon Powers','Slay 5 Undead Brutes within 120 seconds without dying']},
	{name:'Befouled Tomb',links:['The Royal Gardens'],secrets:2,
		normal:['Slay 50 Monsters with ranged attacks','Find 2 Secrets','Slay 80 Monsters without using potions','Slay 80 Monsters within 360 seconds','Slay 50 Monsters without taking damage'],
		elite:['Slay 80 Monsters with Scythe with 5 Active <hex>Hexes</hex>','Slay 3 Forgotten Kings affected by <effect>Daze</effect>','Slay 20 monsters with a single Attack or Demon Power without taking damage','Overkill 35 Skeletons with Shotgun within 30 seconds','Slay 12 Undead Pyromancers within 60 seconds without taking damage']},
	{name:'Sepulcher of the Damned',links:['The Royal Gardens'],secrets:2,
		normal:['Destroy 70 burial urns in the Sepulcher of the Damned','Overkill 15 Skeletons','Slay 30 Monsters with Hammer','Find 2 secrets','Slay 70 Monsters without taking damage'],
		elite:['Slay 7 Ravenous Souls with Bombs','Overkill 60 Monsters with Hand Mortar without Dying','Slay 80 Monsters within 90 seconds with <hex>Hex of Malice</hex>','Slay 35 Monsters with Sword without taking damage and without using Demon Powers','Slay 80 Monsters within 120 seconds with 5 active <hex>Hexes</hex>']},
	{name:'Den of the Broodmother',links:['The Royal Gardens'],secrets:2,
		normal:['Slay 15 Monsters with Lava Creeper\'s Death-Blast','Slay 10 Spider Nests','Slay 5 Spider Matrons','Find 2 Secrets','Slay 500 Spiders with melee attacks'],
		elite:['Slay 150 Spiders affected by <effect>Weakness</effect>','Slay 100 Spiders without taking damage and without using Demon Powers','Slay 8 Spider Nests with Bombs without Dying','Slay 5 Gargantuan Spiders with Lava Creeper\'s Death-Blast','Slay Mordra The Broodmother with 5 active <hex>Hexes</hex>']},
	{name:'The Royal Crypt',links:['The Royal Gardens','Weeping Halls'],secrets:3,
		normal:['Slay 5 Monsters with a single attack or Demon Power','Slay 3 Ravenous Souls','Awaken the restless dead in the sarcophagi across the Royal Crypt','Find 3 Secrets','Slay 50 Monsters within 120 seconds'],
		elite:['Slay 10 Wraiths with 5 active <hex>Hexes</hex>','Slay 80 Monsters With Melee Attacks While Above 80% health','Slay 2 Champions affected by <effect>Cripple</effect>','Slay 80 Monsters without taking damage and without using Demon Powers','Slay 5 Undead Brutes within 120 seconds without dying']},
	{name:'Weeping Halls',links:['The Royal Crypt'],secrets:3,
		normal:['Slay 40 Monsters with Rapier','Find 3 Secrets','Slay 8 Undead Dancers','Slay 4 Spectral Binders with Hammer','Slay 80 Monsters without using potions and Demon Powers'],
		elite:['Slay 100 Monsters without dying and without using Potions, Shrines and Demon Powers','Slay 35 Monsters without dying while you are affected by <effect>Frailty</effect>','Slay 50 Monsters within 120 seconds','Slay Adrian The Fallen with 5 active <hex>Hexes</hex>','Slay Adrian The Fallen without using Potions and Shrines']},
	
	{name:'Bottomless Pit', notes:['Endless randomized PvE battleground', 'Unlocked at level 36', '<npc>GebaN</npc> waits in the starting area.']},
	{name:'Cauldron of Chaos',notes:['Daily changing random dungeon'],
	 	normal:['Slay Lord of the Swamp with <hex>Hex of Malice</hex>, <hex>Hex of Tenacity</hex> and <hex>Hex of Time</hex>','Slay the Tyrant of the Mud-lands with Bombardier Spider\'s barrage attack','Slay the Gate Keeper with Bombardier Spider\'s barrage attack without dying','Slay the Hearts of Fire and Hearts of Ice while you are affected by Frost with 2 active <hex>Hexes</hex> (4)','Slay all Chromatic Essence aspects without dying with 5 active <hex>Hexes</hex>']},
	
	{name:'The Hunting Grounds',links:['The Devil\'s Throat','Widow\'s Mine','Watchtower Ruins','The Tangle','Frostteeth Grotto'],secrets:8,
		normal:['Slay 5 Champions','Slay 5 Essences of Fire with ranged attacks','Find 4 Secrets','Slay 2 Demon Spiders','Slay 8 Essences of Rock with melee attacks'],
		elite:['Slay 10 Essences with Hand Mortar without dying','Slay 3 Champions affected by <effect>Daze</effect>','Slay 100 Monsters without dying and without using Potions with <hex>Hex of Malice</hex>','Slay 50 Monsters with Demon Powers with <hex>Hex of Tenacity</hex>','Slay 6 Wraiths with 5 active <hex>Hexes</hex>']},
	{name:'The Devil\'s Throat',links:['The Hunting Grounds'],secrets:2,
		normal:['Slay 10 Monters with Lava Creeper\'s Death-Blast','Slay 5 Monters with Bombardier Spider\'s Barrage Attack','Slay 10 Essences with <hex>Hex of Time</hex>','Slay 10 Chromathic Essences with melee attacks','Slay 5 Essences without using potions and shrines'],
		elite:['Slay 3 Essences with Bombardier Spider\'s barrage attack with <hex>Hex of Tyranny</hex>','Slay 3 Essence with Lava Creeper\'s death.blast with <hex>Hex of Malice</hex>','Slay 50 Spiders within 60 seconds with <hex>Hex of Malice</hex> and <hex>Hex of Time</hex>','Slay 5 Essences without dying and without using Potions and Shrines','Slay 30 Chromatic Essences without dying with 5 active <hex>Hexes</hex>']},
	{name:'Widow\'s Mine',links:['The Hunting Grounds'],secrets:5,
		normal:['Slay 5 Wraiths with Hammer','Slay 3 Essences of Rock with melee attacks','Find 5 Secrets','Slay 30 Monsters with <hex>Hex of Tenacity</hex>','Slay 50 Monsters within 240 seconds'],
		elite:['Slay 50 Monsters without dying with Hec of Tyranny','Slay 3 Champions with Demon Powers without Dying','Slay 4 Wraiths affected by <effect>Daze</effect>','Slay 20 Monsters within 60 seconds with <hex>Hex of Malice</hex> and <hex>Hex of Time</hex>','Slay 20 Monsters without taking damage and without using Demon Powers']},
	{name:'Watchtower Ruins',links:['The Hunting Grounds'],secrets:2,
		normal:['Slay 40 Monsters within 120 seconds','Overkill 5 Undead Pyromancers','Slay 40 Monsters with <hex>Hex of Malice</hex>','Slay Bane','Slay 30 Monsters without taking damage and without using Demon Powers'],
		elite:['Slay 10 Undead Pyromancers with Demon Powers without dying','Slay 2 Undead Brutes with a single hit with <hex>Hex of Tenacity</hex> and <hex>Hex of Time</hex>','Slay 10 Monsters affected by <effect>Brutality</effect> without dying','Slay 30 monsters within 45 seconds without taking damage','Slay 2 Champions within 45 seconds with 5 active <hex>Hexes</hex>']},
	{name:'The Tangle',links:['The Hunting Grounds'],secrets:2,
		normal:['Slay 20 Monsters','Slay Rachnoss The Host within 180 seconds','Slay Rachnoss The Host without using potions and shrines','Slay Rachnoss The Host with 2 active <hex>Hexes</hex>','Slay Rachnoss The Host while above 80% health without using potions'],
		elite:['Slay 2 Champions with a single hit','Slay Rachnoss The Host within 120 seconds','Slay Rachnoss The Host affected by <effect>Brutality</effect> with <hex>Hex of Tenacity</hex>','Slay Rachnoss The Host without using Shrines and Demon Powers with <hex>Hex of Malice</hex>','Slay Rachnoss The Host with 5 active <hex>Hexes</hex>']},
	{name:'Frostteeth Grotto',links:['The Hunting Grounds'],secrets:2,
		normal:['Find 2 Secrets','Slay 2 Essences of Plague with Rapier','Slay 5 Essences within 240 seconds','Slay Essences with <hex>Hex of Pain</hex>','Slay essences without using potions and Demon Powers'],
		elite:['Slay 2 Essences of Plague affected by <effect>Daze</effect>','Slay 30 Monsters without dying with 5 active <hex>Hexes</hex>','Slay 7 Essences within 180 seconds','Slay Undead Gravedigger without dying and without using Potions and Demon Powers','Slay 10 Undead Soldiers without taking damage']},
		
	{name:'The High Quarter',links:['Lifeless House','Forlorn Chateau'],secrets:6,
		normal:['Find 6 Secrets','Quench 3 gallows flames','Slay Bart, Bundy and Berta','Summon and Slay 20 Evil Lights hidden inside haunted lanterns','Solve the mystery of the Haunted Pumpkin (4)'],
		elite:['Overkill 20 Undead Soldiers without dying with <hex>Hex of Pain</hex> and <hex>Hex of Time</hex>','Slay 10 Sentinels without dying and without using Potions and Shrines','Slay 10 Essences of Magic affected by <effect>Vulnerable</effect> with Scythe','Slay 30 Lesser Gargoyles with Hand Mortar within 180 seconds with <hex>Hex of Malice</hex>','Solve the mystery of the Haunted Pumpkin with 5 active <hex>Hexes</hex>']},
	{name:'Lifeless House',links:['The High Quarter'],secrets:2,
		normal:['Slay 30 Monsters with <hex>Hex of Time</hex>','Slay 30 Monsters While Above 50% helath without using Potions','Slay 30 Monsters with <hex>Hex of Malice</hex> and <hex>Hex of Pain</hex>','Slay Lord Valeri','Slay the Cook within 45 seconds without using Potions'],
		elite:['Slay 60 Monsters with 4 active <hex>Hexes</hex>','Overkill 15 Gargoyles with Sword without dying','Slay 30 Monsters within 90 seconds','Slay 20 Monsters withint 90 seconds with <hex>Hex of Tenacity</hex>','Slay 40 Monsters without taking damage and without using Demon Powers']},
	{name:'Forlorn Chateau',links:['The High Quarter'],secrets:3,
		normal:['Find 3 Secrets','Slay 3 Champions','Slay 40 Monsters with <hex>Hex of Tenacity</hex>','Slay 40 Monsters with Demon Powers','Slay the Volkovs with scythe (2)'],
		elite:['Slay 30 Monsters affected by <effect>Electrocuted</effect> witrh Shotgun','Overkill 20 Monsters with Rapier with a single hit','Slay 30 Monsters affected by <effect>Brutality</effect> without dying','Slay 80 Monsters without dying with 5 active <hex>Hexes</hex>','Slay 2 Vampires within 240 seconds without taking damage']},
 
	{name:'Cemetery Grounds',links:['Deadlight Quarry','Infested Burrow','Forlorn Catacomb','Mausoleum of Bones'],secrets:6,
		notes:['<npc>GebaN</npc> in the NW corner of the map, must be killed'],
		normal:['Slay 25 Gorgoyles with Ranged Attacks','Slay 20 Monsters with Demon Powers','Slay 10 Champions','Slay Dharin the Dreaded Soul','Slay 40 Monsters with <hexHex of Time</hex>, <hex>Hex of Tyranny</hex> and <hexHex of Malice</hex>'],
		elite:['Slay 100 Gargoyles without dying and without using Potions with <hex>Hex of Malice</hex>','Slay 10 Wraiths with Demon Powers with <hex>Hex of Time</hex>','Slay 50 Monsters affected by <effect>Bleeding</effect>','Slay Spite of Ignus with a Ranged Weapon with 5 active <hex>Hexes</hex>','Slay Trust Betrayed with a Melee Weapon with 5 active <hex>Hexes</hex>']},
	{name:'Deadlight Quarry',links:['Cemetery Grounds'],secrets:5,
		normal:['Destroy 100 objects','Slay 20 Monsters with Bombs','Slay 10 Sentinels with Sword','Slay 7 Essences of Lightning with Lighting Gun','Slay 30 Monsters with 3 active <hex>Hexes</hex>'],
		elite:['Slay 100 Monsters with Hammer without dying with <hexHex of Tenacity</hex>','Slay 100 Monsters without dying while you are affected by <effect>Brutality</effect>','Slay 15 Sentinels with Melee Attakcs with 5 active <hex>Hexes</hex>','Slay 10 Essences withint 180 seconds','Slay 50 Monsters without using Potions, Shrines and Demon Powers']},
	{name:'Infested Burrow',links:['Cemetery Grounds'],secrets:2,
		normal:['Slay 10 Spiders with TNT','Slay 20 Spiders with Bombardier Spider\'s barrage attack','Slay 20 Spiders with Lava Creeper\'s death-blast','Slay 4 Demon Spiders within 180 seconds','Slay 70 Spiders without using Potions, Shrines and Demon Powers'],
		elite:['Slay 20 Monsters affected by <effect>Daze</effect> without dying','Slay 50 Monsters with Bombardier Spider\'s barrage attack without dying','Slay 40 Monsters with Bombs without dying and without using Potions and Shrines','Slay 4 Demon Spiders within 180 seconds with <hex>Hec of Malice</hex> and <hex>Hex of Time</hex>','Slay 70 Monsters with 5 active <hex>Hexes</hex>']},
	{name:'Forlorn Catacomb',links:['Cemetery Grounds'],secrets:2,
		normal:['Slay Eisen the Youngest','Slay 4 Essences of Magic with Ranged Attacks','Slay 4 Essences of Plague with Melee Attacks','Slay 50 Monsters with 3 active <hex>Hexes</hex>','Slay 40 Monsters without using Shrines and Demon Powers'],
		elite:['Slay 10 Monsters with a single hit without dying','Slay 5 Wraiths with Demon Powers without dying','Slay 5 Wraiths with Bombs with <hex>Hex of Tenacity</hex>','Slay 3 Essences of Magic without taking damage and without using Demon Powers','Slay Eisen the Youngeset with 5 active <hex>Hexes</hex>']},
	{name:'Mausoleum of Bones',links:['Cemetery Grounds'],secrets:3,
		normal:['Slay the Seven Dwarves (7)','Slay 200 Skeletons within 420 seconds','Slay Vail The Immortal without using Shrines and Demon Powers','Slay Vail The Immortal within 120 seconds','Slay Vail The Immoprtal with 5 active <hex>Hexes</hex>'],
		elite:['Slay 200 Skeletons within 240 seconds','Slay Vail The Immortal with Bombs','Slay Vail The Immortal with Demon Powers within 120 seconds','Slay Vail The Immortal without using Potions and Shrines with <hex>Hex of Malice</hex>','Slay Vail The Immportal while above 50% health with 4 active <hex>Hexes</hex>']},

	{name:'The Onion Quarter',links:['The Hollows','Whispering Burrows','The Ossuary','The Smuggler\'s Stash','The Larder','Defiled Chapel'],secrets:7,
		normal:['Cleanse 8 Infestes Grain Sacks scattered across the slums','Slay 30 Monsters with 2 active <hex>Hexes</hex>','Slay 12 Vampire Thralls within 90 seconds','Slay Scyther in the Rye','Slay Boneclack'],
		elite:['Slay 75 Skeletons with Demon Powers without dying','Slay 100 Monsters within 180 seconds','Slay 6 Wraiths within 90 seconds with <hex>Hex of Malice</hex>','Slay 200 Monsters without dying with 5 active <hex>Hexes</hex>','Slay 1 Demon Spider without dying and without using Potions']},
	{name:'The Hollows',links:['The Onion Quarter'],secrets:2,
		normal:['Find 2 Secrets','Slay 20 Essences with <hex>Hex of Time</hex>','Slay 80 Monsters with <hex>Hex of Tyranny</hex>','Slay 50 Monsters without uding Potions and Demon Powers','Slay 100 Monsters within 320 seconds without using Shrines'],
		elite:['Slay 40 Monsters while your are affectes by <effect>Brutality</effect>','Slay 50 Monsters affected by <effect>Vulnerable</effect> with <hex>Hex of Tenacity</hex>','Slay 3 Champions within 180 seconds','Slay 100 Monsters without dying with 5 active <hex>Hexes</hex>','Slay 100 Monsters within 240 seconds without using Potions and Shrines']},
	{name:'Whispering Burrows',links:['The Onion Quarter'],secrets:3,
		normal:['Find 3 Secrets','Slay 55 Monsters with 3 active <hex>Hexes</hex>','Slay 4 Essences of Plague wuth Hammer with <hex>Hex of Tenacity</hex>','Slay 10 Essences with Lightning Gun','Slay 100 Monsters within 300 seconds with 2 active <hex>Hexes</hex>'],
		elite:['Slay 4 Essences of Plague affected by <effect>Weekness</effect>','Slay 3 Essences of Ice affected by <effect>Frost</effect>','Slay 100 Monsters without dying and without using Potions and Shrines','Slay 100 Monsters without dying with 5 active <hex>Hexes</hex>','Slay 100 Monsters within 240 seconds with 5 active <hex>Hexes</hex>']},
	{name:'The Ossuary',links:['The Onion Quarter'],secrets:3,
		normal:['Find 3 Secrets','Overkill 50 Skeletons','Slay 40 Monsters with a single Attack or Demon Power','Slay 100 Monsters with Demon Poewrs within 180 seconds','Slay 150 Monsters within 240 seconds with 2 active <hex>Hexes</hex>'],
		elite:['Slay 150 Monsters without dying and without using Potions with 2 active <hex>Hexes</hex>','Slay 2 Thrall Hulks with a single hit','Slay 75 Monsters affected by <effect>Brutality</effect> without dying and without using Potions','Slay 100 Monsters without taking damage with 2 active <hex>Hexes</hex>','Slay 150 Monsters within 240 seconds with 5 active <hex>Hexes</hex>']},
	{name:'The Smuggler\'s Stash',links:['The Onion Quarter'],secrets:1,
		normal:['Slay 40 Monsters within 120 seconds','Slay 30 Monsters with Ranged Attakcs within 120 seconds','Slay 2 Champions within 90 seconds','Slay 30 Monsters within 120 seconds without using Potions and Demon Powers','Slay 40 Monsters within 120 seconds with 3 active <hex>Hexes</hex>'],
		elite:['Slay 20 Monsters with Bombs without dying','Slay 40 Monsters within 90 seconds while you are affected by <effect>Brutality</effect>','Slay 40 Monsters within 120 seconds without using Potions or Shrines and Demon Powers','Slay 2 Champions within 45 seconds','Slay 40 Monsters within 120 seconds with 5 active <hex>Hexes</hex>']},
	{name:'The Larder',links:['The Onion Quarter'],secrets:1,
		normal:['Destroy 20 objects within 120 seconds','Slay 30 Monsters with Demon Powers','Slay 45 Monsters with <hex>Hex of Malice</hex> and <hex>Hex of Pain</hex>','Slay Juliet with Lava Creeper\'s death-blast','Slay 45 Monsters within 180 seconds without using Potions'],
		elite:['Slay 45 Monsters without dying with 5 active Hex>Hexes</hex>','Slay Juliet while you are affected by <effect>Weakness</effect>','Slay 20 Monsters affected by <effect>Brutality</effect> without dying','Slay 45 Monsters while above 50% health without using Potions, Shrines and Demon Powers','Slay 30 Monsters within 120 seconds with 3 active <hex>Hexes</hex>']},
	{name:'Defiled Chapel',links:['The Onion Quarter'],secrets:1,
		normal:['Slay The Archivist within 45 seconds without uding Demon Powers and Potions','Slay 50 Monsters within 230 seconds with <hex>Hex of Tenacity</hex>','Slay 70 Monsters with 3 active <hex>Hexes</hex>','Overkill 5 Wraiths','Slay Screeching Calamity within 350 seconds'],
		elite:['Overkill 25 Undead Pyromancers with Shotgun without dying','Slay 10 Monsters with a single hit','Slay 4 Reapers with Scythe without dying','Slay 10 Essences of Flame without dying and without using Potions','Slay 16 of the Wraiths in the final chamber with 5 active <hex>Hexes</hex> without dying']},

	{name:'Secret Pumpkin Level',notes:['You can reach the secret level using a <item rarity="legendary">Pumpkin Pie</item>.'],secrets:3,
		normal:['Find 3 secrets','Slay 5 Trick-or-Treating monster','Slay 2 Demon spiders with lava creeper\'s death-blast','Slay The Barrow King while above 50% health with <hex>Hex of Tenacity</hex>','Slay 9 Vampires with 5 active <hex>Hexes</hex>']},
	{name:'The Well of Worlds',secrets:3,
		normal:['Find 3 Secrets','Slay 100 Monsters without using Potions and Demon Powers','Slay 50 Monsters with a single hit','Overkill 40 Monsters with <hex>Hex of Tenacity</hex>','Slay 3 Dark Knights with 5 active <hex>Hexes</hex>'],
		elite:['Slay 30 Monsters affected by <effect>Daze</effect> without dying','Overkill 50 Skeletoins with Shotung without dying','Overkill 5 Essences of Flame without dying with <hex>Hex of Tyranny</hex>','Slay 3 Dark Knights with Demon Powers with <hex>Hex of Malice</hex> and <hex>Hex of Pain</hex>','Slay 3 Dark KNights without dying and without using Potions and Demon Powers']},
	{name:'Demon World',secrets:2,
		normal:['Find 2 Secrets','Slay Seth','Slay Cruel','Slay Wa-Lee The Solicitor while above 60% health','Slay Wa-Lee The Solicitor with <hex>Hex of Malice</hex>, <hex>Hex of Time</hex> and <hex>Hex of Pain</hex>'],
		elite:['Slay 80 Monsters Spawned by Other Monsters without dying with <hex>Hex of Tyranny</hex>','Slay 7 Champions without dying and without using Potions and Demon Powers with <hex>Hex of Malice</hex> and <hex>Hex of Time</hex>','Slay 16 Demon Seeds without dying with 5 active <hex>Hexes</hex>','Slay Wa-Lee The Solicitor with 4 active <hex>Hexes</hex>','Slay Wa-Lee The Solicitor with 5 active <hex>Hexes</hex>']},

	{name:'The Merchant Quarter',links:['The Cessways','The Freakshow','Heart of Frost','The Gauntlet','The Collector\'s Residence','The Reformatory'],secrets:5,
		notes:['<npc>GebaN</npc> is N of center, must be killed'],
		normal:['Slay Jost a Gargoyle','Slay 5 Thralls with a single Attack or Demon Power','Slay 10 Vampire Acolytes with Ranged Attacks with <hex>Hex of Time</hex>','Slay 20 Monsters withotu using Potions, Shrines and Demon Powers','Overkill 5 Champions'],
		elite:['Slay 10 Vampire Acolytes with Demon Powers without dying','Slay 25 Vampires with Hand Mortar without dying','Slay 10 Vampires affected by <effect>Daze</effect> without dying','Overkill 60 Monsters within 360 seconds','Slay 70 Vampires without dying with 5 active <hex>Hexes</hex>']},
	{name:'The Cessways',links:['The Merchant Quarter'],secrets:2,
		normal:['Open 4 Valves and slay Living Miasma','Slay 5 Reapers with <hex>Hex of Tenacity</hex>','Slay 55 Monsters with <hex>Hex of Tyranny</hex>, <hex>Hex of Time</hex> and <hex>Hex of Malice</hex>','Slay Morenth the Voiceless within 45 seconds with <hex>Hex of Malice</hex>','Slay Tamas Murkvenom within 90 seconds'],
		elite:['Overkill 10 Monsters without dying with <hex>Hex of Malice</hex>','Slay 5 Thrall Hulks affected by <effect>Brutality</effect> without dying','Slay 55 Monsters without dying with 5 active <hex>Hexes</hex>','Slay Morenth the Voiceless while above 50% health with 5 active <hex>Hexes</hex>','Slay Tamas Murkvenom within 60 seconds with 4 active <hex>Hexes</hex>']}, 
	{name:'The Freakshow',links:['The Merchant Quarter'],notes:['PvP arena, unlocked at level 26'],noimage:true},
	{name:'Heart of Frost',links:['The Merchant Quarter'],secrets:1,
		normal:['Slay 50 Monsters with Scythe with <hex>Hex of Tenacity</hex>','Slay 15 Monsters with Bombs','Slay 15 Monsters with Bombardier Spider\'s barrage attack with <hex>Hex of Malice</hex>','Slay 50 Monsters with <hex>Hex of Tyranny</hex> and <hex>Hex of Time</hex>','Slay 40 Monsters while above 50% health with <hex>Hex of Pain</hex>'],
		elite:['Slay 25 Monsters with Bombardier Spider\'s barrage attack while above 50% health','Slay 20 Monsters affected by <effect>Frost</effect> while above 50% health','Slay 30 Monsters with Rapier while above 50% health without using Potions','Slay 70 Monsters without dying with 5 active <hex>Hexes</hex>','Slay 70 Monsters within 240 seconds with 5 active <hex>Hexes</hex>']},
	{name:'The Gauntlet',links:['The Merchant Quarter'],secrets:2,
		normal:['Find 2 Secrets','Reach the end of the corridor within 30 seconds without taking damage and using Demon powers','Slay Cadavros without using Potions, Shrinws and Demon Powers','Slay 6 Shard Sentinels with Ranged Attacks','Slay 20 Monsters within 90 seconds with <hex>Hex of Tyranny</hex>, <hex>Hex of Tenacity</hex> and <hex>Hex of Time</hex>'],
		elite:['Slay 10 Shispering Bones with a single hit without dying with 3 active <hex>Hexes</hex>','Slay 6 Shard Sentineslw tih Hammer without dying with <hex>Hex of Tenacity</hex>','Slay 15 Monsters within 90 seconds with 5 active <hex>Hexes</hex>','Slay Cadavros affected by <effect>Brutality</effect> while above 80% health','Slay Cadavrosd while above 80% health with 4 active <hex>Hexes</hex>']},
	{name:'The Collector\'s Residence',links:['The Merchant Quarter'],secrets:1,
		normal:['Slay 20 Monsters with Shotguns','Slay 15 Monsters with Demon Powers','Slay 5 Monsters with a single Attack or Demon Power','Slay 5 Vampires within 90 seconds','Slay 30 Monsters with 5 active <hex>Hexes</hex>'],
		elite:['Slay 25 Monsters without dying while your are affected by <effect>Brutality</effect>','Slay Passion fo the Collector within 45 seconds with 5 active <hex>Hexes</hex>','Slay 5 Vampires without dying with 5 active <hex>Hexes</hex>','Slay 30 Monsters while above 50% health with 3 active <hex>Hexes</hex>','Slay 15 Monsters with Sword while above 50% health']},
	{name:'The Reformatory',links:['The Merchant Quarter'],secrets:3,
		normal:['Find 3 Secrets','Slay 5 Champions with Sword','Slay 60 Monsters without using Potions','Slay 80 Monsters within 240 seconds','Slay Vondrak within 120 seconds from entering the location'],
		elite:['Slay 50 Monsters affected by <effect>Weakness</effect> without dying','Overkill 3 Champions','Slay 60 Monsters while above 60% health without using Potions','Slay 80 Monsters within 240 seconds with 5 active <hex>Hexes</hex>','Slay 7 Vampires within 90 seconds with <hex>Hex of Malive</hex>']},

	{name:'The Steam Quarter',links:['The Junction','The Stockroom','The Deep Mines','The Shunned Manor'],secrets:4,
		normal:['Slay 20 Vampires with Sword','Slay 10 Champions','Slay 20 Gargoyles with Hamme with <hex>Hex of Tenacity</hex>','Slay 2 Vampire Kings with Demon Powers','Slay 30 Vampires with <hex>Hex of Time</hex> and <hex>Hex of Malice</hex>'],
		elite:['Slay 20 Gargoyles with a single hit without dying','Slay 10 Vampires affected by <effect>Daze</effect> without dying','Slay 7 Thrall Hulks with Hand Mortar without dying with 5 active <hex>Hexes</hex>','Slay 5 Vampire Knights within 120 seconds with 5 active <hex>Hexes</hex>','Slay 10 Champions without dying with 5 active <hex>Hexes</hex>']},
	{name:'The Junction',links:['The Steam Quarter'],secrets:1,
		normal:['Slay 3 Shard Sentinels within 60 seconds','Slay 10 Monsters within 120 seconds','Slay 10 Monsters within 120 seconds with 4 active <hex>Hexes</hex>','Slay 10 Monsters within 120 seconds without using Potions and Demon Powers','Slay 10 Monsters while above 80% health within 240 seconds without using Potions'],
		elite:['Slay 10 Vampires within 120 seconds with 5 active <hex>Hexes</hex>','Slay 10 Vampires while above 60% health with 5 active <hex>Hexes</hex>','Slay 3 Vampires with a single hit without dying','Slay 10 Vampires affected by <effect>Brutality</effect> without dying with 5 active <hex>Hexes</hex>','Slay Vampire Count within 60 seconds with 5 active <hex>Hexes</hex>']},
	{name:'The Stockroom',links:['The Steam Quarter'],secrets:2,
		normal:['Slay Viscount Mornai within 60 seconds','Slay 100 Monsters with <hex>Hex of Malice</hex>, <hex>Hex of Tenacity</hex> and <hex>Hex of Time</hex>','Overkill 50 Monsters within 180 seconds','Slay 80 Monsters while above 60% health within 180 seconds without using Demon Powers','Slay 40 Monsters without taking damage and without using Demon Powers'],
		elite:['Slay Viscount Mornai within 60 seconds with 5 active <hex>Hexes</hex>','Slay 120 Monsters without dying with 5 active <hex>Hexes</hex>','Slay 4 Vampires with Lava Creeper\'s death-blast without dying','Slay 40 Monsters without taking damage and without using Demon Powers with 3 active <hex>Hexes</hex>','Slay 80 Monsters within 120 seconds with <hex>Hex of Malice</hex>, <hex>Hex of Time</hex> and <hex>Hex of Tyranny</hex>']},
	{name:'The Deep Mines',links:['The Steam Quarter'],secrets:1,
		normal:['Find 1 Secret','Slay 4 Dark Knights with <hex>Hex of Tenacity</hex>','Slay 10 Essences with <hex>Hex of Time</hex>','Slay 50 Monsters with <hex>Hex of Tyranny</hex>','Slay 50 Monsters without using Potions with <hex>Hex of Malice</hex>'],
		elite:['eSlay 4 Dark Knights affected by <effect>Weakness</effect> without dying','Slay 30 Monsters affected by <effect>Electrocuted</effect> with Rapier without dying','Slay 3 Champions with Demon Powers without dying','Overkill 30 Monsters without dying and without using Potions','Slay the Magnificent Miners without dying with 5 active <hex>Hexes</hex>']},
	{name:'The Shunned Manor',links:['The Steam Quarter','Sanctum Sanctorum'],secrets:3,
		normal:['Slay 20 Lesser Gargoyles with a single hit','Slay 5 Spiders with Demon Powers','Slay Dead Timmy','Slay 4 Vampire Knights within 600 seconds','Slay Fester the Butler without dying'],
		elite:['Slay 200 Monsters while above 50% health with 3 active <hex>Hexes</hex>','Slay 3 Vampire Kings with Bombs without dying','Slay the Inner Guardian without using Potions and Shrinws and without dying','Slay the 8 Dinner Guests with Shotgun and <hex>Hex of Malice</hex> without dying','Slay Fester the Butler with Lava Creeper\'s death-blast']},
	{name:'Sanctum Sanctorum',links:['The Shunned Manor'],secrets:3,
		normal:['Find 3 Secrets','Slay 30 Miscreations with Shotgun','Slay 12 Vampiric Titems with Hand Mortar','Slay Lord Gabriel with 3 active <hex>Hexes</hex>','Slay Lord Gabriel without dying and without using Shrines'],
		elite:['Slay 45 Miscreations without dying with 5 active <hex>Hexes</hex>','Slay Lord Gabriel in Stage 1 within 240 seconds without dying','Slay Lord Gabirel in Stage 2 while above 50% health without using Shrines','Slay Lord Gabriel in Stage 3 while he is affected by <effect>Brutality</effect>','Slay Lord Gabriel in Stage 3 without dying with 5 active <hex>Hexes</hex>']},
	
	{name:'The Pub at the End of Time',dlc:2,secrets:0,notes:['The Pub at the End of Time is the hub of the Mot&ouml;rhead campaign.']},
	
	{name:'The World of Wars',dlc:2,links:['Bedeviled Vault','Wicked Garrison','The Furnace','Heart of Destruction'],monuments:3,
		secret:[[254,327],[153,188],[100,214],[118,117],[264,81],[330,48],[646,140],[431,494],[551,485],[546,551],[257,623]],
		normal:['Use 10 Demon Powers','Overkill 30 Skeletons','Slay 15 Succubi Firestarters with Ranged Attacks','Slay the 2 Devil\'s Hounds','Slay 3 Champions'],
		elite:['Overkill 150 Monsters with Guitar','Slay the Napalm Queen with 5 active <hex>Hexes</hex>','Slay 5 Reapers with Demon Powers','Slay 10 Champions without using Potions','Slay 2 Firestorms while affected by <effect>Frailty</effect> without dying']},
	{name:'Bedeviled Vault',dlc:2,links:['The World of Wars'],monuments:2,
		secret:[[335,311],[314,601]],
		normal:['Find 2 Secrets','Slay the 2 Cleansing Ones','Slay 30 Hellhounds with Ranged Attacks','Slay 5 Forgotten Kings without using Potions or Shrines','Slay 2 Hellhound Omegas within 120 seconds'],
		elite:['Slay 40 Hellhounds with Ranged Attacks within 120 seconds','Slay 5 Forgotten Kings within 120 seconds without using Potions','Slay the 2 Cleansing Ones with 4 active <hex>Hexes</hex> within 120 seconds','Slay 100 Monsters with Guitar within 120 seconds with 4 active <hex>Hexes</hex>','Slay 2 Hellhound Omegas with Demon Powers within 120 seconds']},
	{name:'The Furnace',dlc:2,links:['The World of Wars'],monuments:2,
		secret:[[232,94],[307,236]],
		normal:['Find 2 Secrets','Overkill 20 Essences of Flame','Overkill 5 Succubi Firestarters within 90 seconds','Slay the 6 monsters fromthe final waves of all Monuments of Rock','Slay Hellhouns Alpha without using Potions and Demon Powers'],
		elite:['Overkill 30 Essences with 5 active <hex>Hexes</hex>','Slay 15 Succubi Firestarters while you are affected by <effect>Brutality</effect>','Slay 50 Monsters without dying and withtout using Potions and Demon Powers','Slay 70 Monsters within 180 seconds with 5 active <hex>Hexes</hex>','Slay Hellhouns Alpha while above 80% health without using Potions']},
	{name:'Wicked Garrison',dlc:2,links:['The World of Wars'],monuments:2,
		secret:[[134,158],[296,259],[661,187]],
		normal:['Find 3 Secrets','Slay Murderlady','Slay Succubus Swordmaiden with Sword','Slay 15 Monsters within 120 seconds while you are affected by <effect>Brutality</effect>','Slay the 2 Nightmares without using Potions'],
		elite:['Overkill 30 Essences within 120 seconds','Slay Murderlady with 5 active <hex>Hexes</hex>','Slay Succubus Swordmaiden without dying and without using Potions','Slay 4 Dark Knights while above 50% health','Slay 40 Monsters without taking damage']},
	{name:'Heart of Destruction',dlc:2,links:['The World of Wars'],
		notes:['Arena of area boss Warpig Machine'],
		normal:['Slay Warpig Machine with Guitar','Slay Warpig Machine with Demon Powers','Slay Warpig Machine within 240 seconds','Slay Warpig Machine while above 50% health','Slay Warpig Machine without using Potions'],
		elite:['Slay Warpig Machine with Demon Powers within 120 seconds','Slay Warpig Machine with 5 acitve <hex>Hexes</hex>','Slay Warpig Machine while above 50% health without using Potions','Slay Warpig Machine without using Potions with <hex>Hex of Malice</hex>','Slay Warpig Machine withtout taking damage with 4 active <hex>Hexes</hex>']},
	
	{name:'The Weird West',dlc:2,links:['Dead Man\'s Mine','Windswept Canyon','Vanishing Wellspring','Terminus Est'],monuments:3,
		secret:[[289,24],[516,13],[19,304],[165,217],[502,293],[208,585],[437,503],[473,632]],
		normal:['Slay the Bad One','Slay the Deputy with melee attack','Slay the Sheriff with Ranged Attack','Slay the Hermit with Bomb','Slay Snake Fang\'s Spirit with Demon Power'],
		elite:['Slay 20 Undead Soldiers while above 50% health without using Potions','Slay 10 Scorpion Bahers affected by <effect>Brutality</effect> with <hex>Hex of Malice</hex>','Slay 8 Undead Fools while you are affected by <effect>Frailty</effect>','Slay 2 Hellhound Alphas without dying with 5 active <hex>Hexes</hex>','Slay 10 Champions with 5 active <hex>Hexes</hex>']},
	{name:'Dead Man\'s Mine',dlc:2,links:['The Weird West'],monuments:1,
		secret:[[480,64],[395,430],[616,505]],
		normal:['Find 3 Secrets','Slay 4 Scorpion Earthshakers with Guitar','Slay 2 Scorpion Bullies with Revolvers','Slay 2 Succubus Virtuoso Champions','Slay Emerancia Sunkenshire with Demon Powers'],
		elite:['Overkill 12 Cassidy Boys withtout dying','Slay 5 Scorpion Champions with 5 active <hex>Hexes</hex> without dying','Slay Miner\'s Madness within 120 seconds with 5 active <hex>Hexes</hex>','Slay 3 Succubus Swordmaiden Champions with Melee Attacks without dying','Slay 3 Hellhound Alphas with Ranged Attacks without dying']},
	{name:'Windswept Canyon',dlc:2,links:['The Weird West'],monuments:2,
		secret:[[59,569],[541,376]],
		normal:['Overkill 100 Monsters','Slay 10 Scorpion Barragers within 120 seconds','Slay Treachery with Ranged attacks without using Demon Powers and Shrines','Slay the 2 Serpentine Ladies','Slay the 6 Prejudiced Ones with a Guitar'],
		elite:['eSlay 10 Scorpion Barragers without taking damage','Slay 9 Scorpion Artilleries while above 50% health','Slay 10 Champions with Ranged attakcs while above 50% health','Slay Treachery without using Potions while above 50% health','Slay the 6 Prefudices Ones with 5 active <hex>Hexes</hex> within 180 seconds']},
	{name:'Vanishing Wellspring',dlc:2,links:['The Weird West'],monuments:2,
		secret:[[322,160],[504,142],[579,338]],
		normal:['Find 3 Secrets','Slay 50 Monsters with Revolvers','Slay Death','Slay 15 Succubi while you are affected by <effect>Brutality</effect>','Slay 30 Succubi Firestarters within 180 seconds'],
		elite:['Slay 50 Monsters affected by <effect>Brutality</effect>','Slay 3 Reapers within 120 seconds with <hex>Hex of Malice</hex>','Slay 2 Demon Spiders without dying with 5 active <hex>Hexes</hex>','Slay Scorpion Earthshaker within 60 seconds','Slay 2 Demon Spiders without dying and without using Potions']},
	{name:'Terminus Est',dlc:2,links:['The Weird West'],
		notes:['Arena of area boss Orgasmatron'],
		normal:['Slay 200 Monsters','Slay Orgasmatron with Revolvers','Slay Orgasmatron with Melee Attacks','Slay Orgasmatron within 300 seconds','Slay Orgasmatron while above 50% health'],
		elite:['Slay 50 Monsters with a single attack or Demon Power','Slay Orgasmatron with <hex>Hex of Tyranny</hex>','Slay Orgasmatron with 5 active <hex>Hexes</hex>','Slay Orgasmatron within 240 seconds with <hex>Hex of Tenacity</hex>','Slay Orgasmatron while above 50% health with <hex>Hex ot Malice</hex>']},
	
	{name:'The Dark Ages',dlc:2,links:['Diseased Cellar','Frozen Hearth Cave','The Slaughterhouse','Screaming Pathway'],monuments:3,
		secret:[[651,30],[278,123],[669,288],[540,597],[289,660],[28,555]],
		normal:['Find 6 Secrets','Slay the 2 Bloodgreed Spiders with Demon Powers','Slay the Iron Lady with Melee attacks','Slay The Extorter with Ranged Attacks','Slay the 4 Everwatch with <hex>Hex of Malice</hex> and <hex>Hex of Tenacity</hex>'],
		elite:['Slay 15 Champions without dying with <hex>Hex of Malice</hex>','Slay the 2 Bloodgreed spiders without using Potions','Slay the Iron Lady without dying while she is affected by <effect>Brutality</effect>','Slay the Extorter while above 50% health','Slay the Castellan with a Guitar with 5 active <hex>Hexes</hex>']},
	{name:'Diseased Cellar',dlc:2,links:['The Dark Ages'],monuments:2,
		secret:[[297,35]],
		normal:['Slay 2 Succubus Swordmaidens','Slay Succubus Hound Mistresses with Melee Attacks','Slay 2 Succubus Witches with Ranged Attacks','Slay 2 Succubus Virtuosi without using Shrines','Slay the Abomination without using Potions'],
		elite:['eSlay 2 Succubus Virtuosi with 5 active <hex>Hexes</hex>','Slay 25 Hellhounds spawned by other Monsters without dying','Slay 2 Succubus Witches with Melee Attacks','Slay 2 Succubus Wirtuosi while above 50% health with <hex>Hex of Tyranny</hex>','Slay the Abominsation within 320 seconds with 5 active <hex>Hexes</hex>']},
	{name:'Frozen Hearth Cave',dlc:2,links:['The Dark Ages'],monuments:2,
		secret:[[670,297],[180,380]],
		normal:['Slay 10 Champions','Slay Herja with a Tome','Slay Fenrir with a Hammer','Dlsay the 3 champion Corrupted Norns with Revolvers','Slay Hlokk with a Guitar'],
		elite:['Slay 8 Champions within 300 seconds','Slay 30 Spiders spawned by other Monsters with <hex>Hex of Time</hex> and <hex>Hex of Tyranny</hex>','Slay the 3 champion Corrupted Norns with Melee attacks with 5 active <hex>Hexes</hex>','Slay Hlokk with Ranged attakc with 5 active <hex>Hexes</hex>','Slay Nidhogg with 5 active <hex>Hexes</hex> without dying']},
	{name:'The Slaughterhouse',dlc:2,links:['The Dark Ages'],monuments:1,
		secret:[[477,68],[551,249]],
		normal:['Find 2 Secrets','Slay 3 Succubus Swordmaidens with Demon Powers','Slay 3 Succubus Witches while your are affected by <effect>Brutality</effect>','Slay Lady Erzrbrth within 360 seconds','Slay Soulfikar without using Potions and Demon Powers'],
		elite:['Slay 50 Monsters with Demon Powers while above 50% health','Slay 40 Succubi without dying and without using Potions and Shrines','Slay Andrey with 5 active <hex>Hexes</hex> without dying','Slay Lady Erezebeth without dying and without using Potions and Shrines','Slay Soulfikar within 360 seconds with 5 active <hex>Hexes</hex>']},
	{name:'Screaming Pathway',dlc:2,links:['The Dark Ages','The Chalice'],monuments:2,
		secret:[[242,11],[613,32],[229,464]],
		normal:['Slay 3 Vampire Knights without tyking damage','Slay Siena while above 50% health without using Potions','Slay 3 Tyrant Succubus Swordmaidens','Slay Zeal with Demon Powers','Slay the 2 Sisters of Mercy without using Potions'],
		elite:['eSlay 3 Vampire Knights within 180 seconds without taking damage','Slay Siena while above 50% health without using Potions and Shrines','Slay 4 Tyrant Succubus Swordmaidens with <hex>Hex of Malice</hex>','Slay Zeal with Demon Powers without dying with <hex>Hex of Tyranny</hex>','Slay the 2 Sisters of Mercy without using Potions with 5 active <hex>Hexes</hex>']},
	{name:'The Chalice',dlc:2,links:['Screaming Pathway'],
		notes:['Arena of area boss Queen of the Damned'],
		normal:['Slay Queen of the Damned with Revolvers','Slay Queen of the Damned with Guitars','Slay 10 Champions','Slay Queen of the Damned with 3 active <hex>Hexes</hex>','Slay Queen of the Damned without using Potions and Shrines'],
		elite:['Slay Queen fo teh Damned with <hex>Hex of Tyranny</hex>','Slay 25 Champions','Slay Queen of the Damned within 360 seconds','Slay Queen of the Damned while above 50% health','Slay Queen of the Damned without dying qith 5 active <hex>Hexes</hex>']},

	{name:'The Locus',dlc:1,notes:['The Locus is the hub of the Fractured Worlds campaign.']},
	{name:'The Fracture',dlc:1,notes:['Randomly generated infinite dungeon that changes every day.','Last known location of <item rarity="legendary">the Frame of the Astrolabe</item> on tier 10 and more <item rarity="legendary">Shard of the Astrolabe</item> on tier 25 and tier 50.','Chests can appear randomly, too.'],noimage:true},
	{name:'Hanging Gardens of Ea',dlc:1,notes:['Randomly generated single level dungeon that changes every day.','Contains <item rarity="legendary">Shard of the Astrolabe</item>'],noimage:true},
	{name:'Cadaver City',dlc:1,notes:['Randomly generated single level dungeon that changes every day.','Contains <item rarity="legendary">Shard of the Astrolabe</item>'],noimage:true},
	{name:'Amaranthine Autumn',dlc:1,notes:['Randomly generated single level dungeon that changes every day.','Contains <item rarity="legendary">Shard of the Astrolabe</item>'],noimage:true},
	{name:'Lethean Caves',dlc:1,notes:['Randomly generated single level dungeon that changes every day.','Contains <item rarity="legendary">Shard of the Astrolabe</item>'],noimage:true},
];