const prefix = [
	{name:'Cursed', attributes:['Damage increased by <max>44</max>%.','While equipped: Minimal gold drops (all gold drops are reduced to 1 gold)'],
		recipe:['Dark Mist','Dark Mist','Berserk Aura']},
	{name:'Dancing', attributes:['Attack speed increased by <max>22</max>%'],
		recipe:['Boomerang','Boomerang','Blink']},
	{name:'Devastating', attributes:['Damage increased by <max>28</max>%'],
		recipe:['Berserk Aura','Berserk Aura','Berserk Aura']},
	{name:'Efficient', attributes:['<max>44</max>% faster weapon skill cooldowns'],
		recipe:['Blink','Blink','Boomerang']},
	{name:'Elder', attributes:['While equipped: Gain <max>56</max>% more XP'],
		recipe:['Boomerang','Diamond','Dark Mist']},
	{name:'Essence Slayer\'s', attributes:['+<max>56</max>% damage against essences'],
		recipe:['Sunray','Shockwave','Dark Mist']},
	{name:'Executioner', attributes:['Damage is increased by <max>40</max>% when health is above 90%'],
		recipt:['Berserk Aura','Purging Flame','Pull']},
	{name:'Gargoyle Slayer\'s', attributes:['+<max>56</max>% damage against gargoyles'],
		recipe:['Pull','Pull','Purging Flame']},
	{name:'Gided', attributes:['Gold cost increases <max>4</max> times']},
	{name:'Greedy', attributes:['While equipped: Monsters drop <max>116</max>% more gold'],
		recipe:['Diamond','Diamond','Time Bubble']},
	{name:'Inquisitor', attributes:['Damage increased by <max>40</max>% when the overdrive meter is full'],
		recipe:['Berserk Aura','Purging Flame','Sunray']},
	{name:'Piercing', attributes:['+<max>66</max> armor penetration'],
		recipe:['Sunray','Sunray','Pull']},
	{name:'Skeleton Slayer\'s', attributes:['+<max>56</max>% damage against skeletons'],
		recipe:['Boomerang','Boomerang','Meteor']},
	{name:'Spider Slayer\'s', attributes:['+<max>56</max>% damage against spiders'],
		recipe:['Boomerang','Boomerang','Purging Flame']},
	{name:'Survivor', attributes:['Damage is increase by <max>50</max>% when health is below 50%'],
		recipe:['Berserk Aura','Purging Flame','Diamond']},
	{name:'Vampire Slayer\'s', attributes:['+<max>56</max>% damage against vampires'],
		recipe:['Pull','Pull','Sunray']},
	{name:'Vicious', attributes:['Critical damage increased by <max>112</max>%'],
		recipe:['Purging Flame','Purging Flame','Purging Flame']},
	{name:'Wrath Slayer\'s', attributes:['+<max>56</max>% damage against wraiths'],
		recipe:['Sunray','Shockwave','Purging Flame']},
	{name:'Zealous', attributes:['Overdrive meter fills <max>110</max>% faster'],
		recipe:['Time Bubble','Time Bubble','Sunray']},
];
const suffix = [
	{name:'Assassin', attributes:['Critical chance increased by <max>22</max>%'],
		recipe:['Meteor','Meteor','Meteor']},
	{name:'Bear', attributes:['Critical hits knock back enemies (5 sec. cooldown)'],
		recipe:['Shockwave','Shockwave','Meteor']},
	{name:'Duelist', attributes:['+<max>66</max> armor penetration']},
	{name:'Extraordinary Luck', attributes:['While equipped: Find better items']},
	{name:'Fox', attributes:['Attack cooldowns reduced by <max>3.4</max> secs on overkill (1 sec. cooldown)'],
		recipe:['Time Bubble','Time Bubble','Blink']},
	{name:'Leech', attributes:['Gain <max>8.5</max>% of max health on crit (5 sec. cooldown)'], value:'float',
		recipe:['Sanguine Aura','Sanguine Aura','Meteor']},
	{name:'Luck', attributes:['While equipped: Find <max>34</max>% more items'],
		recipe:['Diamond','Blink','Time Bubble']},
	{name:'Mauling', art:'of', attributes:['Knock back ennemies with <max>22</max>% chance'],
		recipe:['Shockwave','Shockwave','Shockwave']},
	{name:'Ram', attributes:['Inflict Daze on crit (<max>X</max> sec cooldown)'],
		recipe:['Pull','Pull','Meteo']},
	{name:'Value', attributes:['Gold cost increases <max>X</max> times']},
	{name:'Vampirism', art:'of', attributes:['Gain <max>68</max> health on hit'],
		recipe:['Sanguine Aura','Sanguine Aura','Sanguine Aura']},
	{name:'Vulture', art:'of the', attributes:['Gain <max>330</max> health on overkill (5 sec. cooldown)'],
		recipe:['Sanguine Aura','Sanguine Aura','Blink']},
	{name:'Wolf', art:'of the', attributes:['Inflict <effect>Vulnerable</effect> with <max>34</max>% chance'],
		recipe:['Dark Mist','Dark Mist','Dark Mist']},
];