const stones = [
	{name:'Power Stone of Ardor', effect:['Use in Transmutation to improve the triggering rate of a talisman']},
    {name:'Power Stone of Armor', effect:['User in Transmutation to improce the armor of an outfit']},
	{name:'Power Stone of Accuracy', effect:['Use in Transmutation to improce the citical chance of a weapon']},
	{name:'Power Stone of Damage', effect:['Use in Transmutation to improve the damage of a weapon']},
	{name:'Dancing Power Stone', effect:['Use in Transmutation to add or improve the <effect>Dancing</effect> property of an uncommon or rare weapon']},
	{name:'Devastating Power Stone', effect:['Use in Transmutation to add or improve the <em>Devastating</em> property of an uncommon or rare weapon', '<em>Devastating</em>: Increases damage']},
	{name:'Power Stone of Divinity', effect:['User in Transmutation to improve the divine property of a destiny card or to add divine property to a normal destiny card']},
    {name:'Power Stone of Demon Power', effect:['Use in Transmutation to improve the primary and secondary property of a Demon Power']},
	{name:'Elder Power Stone', effect:['Use in Transmutation to add or improve the <effect>Elder</effect> orioerty of an uncommon or rare weapon']},
    {name:'Executioner\'s Power Stone', effect:['Use in Transmutation to add or improve the <effect>Executioner\'s</effect> property to an uncoommon or rare weapon','<effect>Executioner\'s</effect>: Increases damage when health is above 90%']},
	{name:'Power Stone of Fervor', effect:['Use in Transmutation to improve the secondary property of an outfit']},
	{name:'Inquisitor\'s Power Stone', effect:['Use in Transmutation to add or imporive the <effect>Inquisitor\'s</effect> property of an uncommon or rare weapon.']},
	{name:'Power Stone of the Leech', effect:['Use in Transmutation to add or improve the <effect>of the Leech</effect> property of an uncommon or rare weapon']},
	{name:'Piercing Power Stone', effect:['Use in Transmutation to add or improve the <effect>Piercing</effect> orioerty of an uncommon or rare weapon']},
    {name:'Skeleton Slayer\'s Power Stone', effect:['Use in Transmutation to add or improve the <effect>Skeleton Slayer\'s</effect> property of an uncommon or rare weapon','<effect>Skeleton Slayer\'s</effect>: Increases damage against skeletons']},
	{name:'Power Stone of Smiting', effect:['Use in Transmutation to improve the effect of a talisman']},
	{name:'Power Stone of Vampirism', effect:['Use in Transmutation to add or improve <effect>of Vampirism</effect> property of an uncommon or rare weapon']},
	{name:'Power Stone of Wickedness', effect:['Use in Transmutation to improve the wicked property of a destiny card or to add a wicke dproperty to a normal destiny card']},
	// {name:'', effect:['']},
];
