const talismans = [
	{name:'Antique', rarity:"legendary", attributes:['All enemies within <max>5-11</max> m radius and in line of sight turn into dancing skeletons and then die.','Doesn\'t affect Champions, Bosses or Tyrants.'], 
		recipe:['<power rarity="legendary">Blink</power>','<item rarity="legendary">Lucky Rabbit\'s Foot</item>','<talisman>Curio</talisman>']},
	{name:'Appartus', rarity:"legendary", attributes:['All enemies within 10m radius become <effect>Electrocuted</effect> for <max>10-34</max> sec.','A number of ball lightnings appear and start targeting <effect>Electrocuted</effect> enemies'], 
		recipe:['<power rarity="legendary">Blink</power>','<i class="legendary">legendary lightning gun</i>','<talisman>Gadget</talisman>']},
	{name:'Artifact', rarity:"legendary", attributes:['All attacks are critical hits for the next <max>15-33</max> sec.'], 
		recipe:['<weapon rarity="legendary" type="Sword">Kladenets</weapon>','<item rarity="legendary">Legendary Dye</item>','<talisman>Idol</talisman>']},	
	{name:'Boon', rarity:"rare", attributes:['Gain several positive conditions for <max>20-44</max> sec'], 
		recipe:['<power rarity="legendary">Sanguine Aura</power>','<item rarity="rare">White Dye</item>','<talisman>Charm</talisman>']},
	{name:'Charm', rarity:"uncommon", attributes:['Gain Invulnerability for <max>7-13</max> sec.'], 
		recipe:['<item rarity="uncommon">Ambrosia</item>','<power radius="common">Sanguine Aura</power>','<card rarity="uncommon">The Sun</card>']},
	{name:'Curio', rarity:'rare', attributes:['All attacks <effect>Daze</effect> enemies for <max>20-68</max> sec.'], 
		recipe:['<card>The Fool</card>','<img src="../img/dp/any_l.png" alt="any legendary demon power" title="any legendary demon power"/>','<talisman rarity="uncommon">Trinket</talisman>']},
	{name:'Effigy', rarity:'uncommon', attributes:['Killed enemies leace exploding pumpkins damaging other enemies for the next <max>15-33</max> sec.'], 
		recipe:['<item rarity="rare">Aether Vial</item>','<card>The Vampire</card>','<power rarity="rare">Berserk Aura</power>']},
	{name:'Flame', rarity:'uncommon', attributes:['Releases 5 fireballs towards the nearest enemies.','Each fireball creates fiery explosion on hit dealing (~22% of weapon damage) damage.'], 
		recipe:['<item rarity="uncommon">Fire Bomb</item>','<power>Meteor</power>','<card rarity="rare">Greed</card>']},
	{name:'Ember', rarity:"rare", attributes:['Causes a fierce explosion, dealing (~68% of weapon damage) damage and inflict <effect>Burning</effect> condition to all enemies in 5 m radius.'], 
		recipe:['<power rarity="legendary">Sunray</power>','<item>Red Dye</item>','<talisman>Flame</talisman>']},
	{name:'Gadget', rarity:"rare", attributes:['All enemies in 10m radius become <effect>Electrocuted</effect> for <max>10-34</max> sec.','Lightning strike hit nearby <effect>Electrocuted</effect> enemies.'], 
		recipe:['<power rarity="rare">Dark Mist</power>','<card rarity="legendary">The Lightning</card>','<talisman>Gizmo</talisman>']},
	{name:'Gizmo', rarity:'uncommon', attributes:['All enemies in 10m radius become <effect>Electrocuted</effect> for <max>20-44</max> sec.'], 
		recipe:['<item rarity="uncommon">Flash Bomb</item>','<i class="">rare lightning gun</i>','<card rarity="rare">Wildcard</card>']},
	{name:'Idol', rarity:'rare', attributes:['Gain <effect>Brutality</effect> for <max>60-132</max> sec.'], 
		recipe:['<power rarity="legendary">Berserk Aura</power>','<item rarity="rare">Black Dye</item>','<talisman rarity="uncommon">Effigy</talisman>']},
	{name:'Phoenix', rarity:"legendary", attributes:['Teleport to another place causing fierce explosions on both ends.','Each explosion deals (~22% of weapon damage) damage to each monster in 3m radius.'], 
		recipe:['<weapon rarity="legendary" type="Hammer">Meteor</weapon>','<card rarity="legendary">The Sun</card>','<talisman>Ember</talisman>']},
	{name:'Relic', rarity:"legendary", attributes:['Full heal.','Each hit is an instan kill for the next <max>7-13</max> sec.','Doesn\'t affect Champions, Bosses or Tyrants.'], 
		recipe:['<card rarity="rare">Justice</card>','<item rarity="legendary">Legendary Dye</item>','<talisman>Boon</talisman>']},
	{name:'Trinket', rarity:'uncommon', attributes:['Applies the <effect>Slow</effect> condition to all enemies in 10m radius for <max>20-44</max> sec.'], 
		recipe:['<i class="common">common weapon</i>','<card>The Fool</card>','<i class="rare">rare demon power</i>']},
];
const triggers = [
	{name:'Barbaric', trigger:'Charge with <max>100-340</max> Energy per Special Weapon attack'},
	{name:'Bastion', trigger:'Charge with <max>50-110</max> Energy per Deflected Attack'},
	{name:'Brute', trigger:'Charge with <max>0.10-0.28</max> Energy per 1 Damage Dealt'},
	{name:'Egotistical', trigger:'Charge with <max>100-460</max> Energy per Positive Condition Gained'},
	{name:'Fatal', trigger:'Charge with <max>15-51</max> Energy per Critical Hit'},
	{name:'Gluttonous', trigger:'Charge with <max>500-1100</max> Energy per Loot Picked Up'},
	{name:'Healer', trigger:'Charge with <max>3-11</max> Energy per ***1% Of Maximum Health*** Points of Health Restored'},
	{name:'Holy Warrior', trigger:'Charge with 200 Energy per second While Having <max>3-1</max> Positive Conditions'},
	{name:'Peasant', trigger:'Charge with <max>25-55</max> Energy per Basic Weapon attack'},
	{name:'Precarious', trigger:'Charge with 200 Energy per second While Below <max>40-76</max>% Health'},
	{name:'Precise', trigger:'Charge with <max>50-110</max> Energy per Split-timed Attack'},
	{name:'Ruinous', trigger:'Charge with <max>340-340</max> per Overkill'},
	{name:'Sorcerous', trigger:'Charge with <max>200-320</max> Energy per Demon Power used'},
	{name:'Tinkerer', trigger:'Charge with <max>350-530</max> Energy per Consumable Used'},
];