const talismans = [
	{name:'Antique', rarity:"legendary", attributes:['All enemies within (5-11) m radius and in line of sight turn into dancing skeletons and then die.','Doesn\'t affect Champions, Bosses or Tyrants.'], 
		recipe:['','','']},
	{name:'Appartus', rarity:"legendary", attributes:['All enemies within 10 m radius become <effect>Electrocuted</effect> for (10-34) sec.','A number of ball lightnings appear and start targeting <effect>Electrocuted</effect> enemies'], 
		recipe:['','','']},
	{name:'Artifact', rarity:"legendary", attributes:['All attacks are critical hits for the next (15-33) sec.'], 
		recipe:['','','']},	
	{name:'Boon', rarity:"rare", attributes:['Gain several positive conditions for (20-44) sec'], 
		recipe:['','','']},
	{name:'Charm', rarity:"uncommon", attributes:['Gain Invulnerability for (7-13) sec.'], 
		recipe:['<item rarity="uncommon">Ambrosia</item>','<power radius="common">Sanguine Aura</power>','<card rare="uncommon">The Sun</card>']},
	{name:'Curio', rarity:'rare', attributes:['All attacks <effect>Daze</effect> enemies for (20-68) sec.'], 
		recipe:['<card>The Fool</card>','<i class="legendary">legendary demon power</i>','<talisman rarity="uncommon">Trinket</talisman>']},
	{name:'Effigy', rarity:'uncommon', attributes:['Killed enemies leace exploding pumpkins damaging other enemies for the next (15-33) sec.','Charge with 15 Energy per critical hit'], 
		recipe:['<item rarity="rare">Aether Vial</item>','<card>The Vampire</card>','<power rarity="rare">Berserk Aura</power>']},
	{name:'Flame', rarity:'uncommon', attributes:['Releases 5 fireballs towards the nearest enemies.','Each fireball creates fiery explosion on hit dealing (~22% of weapon damage) damage.'], 
		recipe:['<item rarity="uncommon">Fire Bomb</item>','<power>Meteor</power>','<card rarity="rare">Greed</card>']},
	{name:'Ember', rarity:"rare", attributes:['Causes a fierce explosion, dealing (~68% of weapon damage) damage and inflict <effect>Burning</effect> condition to all enemies in 5 m radius.'], 
		recipe:['','','']},
	{name:'Gadget', rarity:"rare", attributes:['All enemies in 10m radius become <effect>Electrocuted</effect> for (10-34) sec.','Lightning strike hit nearby <effect>Electrocuted</effect> enemies.'], 
		recipe:['','','']},
	{name:'Gizmo', rarity:'uncommon', attributes:['All enemies in 10m radius become <effect>Electrocuted</effect> for (20-44) sec.','Charge with 350 Energy per Consumable used'], 
		recipe:['<item rarity="uncommon">Flash Bomb</item>','<i class="">rare lightning gun</i>','<card rarity="rare">Wildcard</card>']},
	{name:'Idol', rarity:'rare', attributes:['Gain <effect>Brutality</effect> for (60-132) sec.'], 
		recipe:['<power rarity="legendary">Berserk Aura</power>','<item rarity="rare">Black Dye</item>','<talisman rarity="uncommon">Effigy</talisman>']},
	{name:'Phoenix', rarity:"legendary", attributes:['Teleport to another place causing fierce explosions on both ends.','Each explosion deals (~22% of weapon damage) damage to each monster in 3m radius.'], 
		recipe:['','','']},
	{name:'Relic', rarity:"legendary", attributes:['Full heal.','Each hit is an instan kill for the next (7-13) sec.','Doesn\'t affect Champions, Bosses or Tyrants.'], 
		recipe:['','','']},
	{name:'Trinket', rarity:'uncommon', attributes:['Applies the <effect>Slow</effect> condition to all enemies in 10m radius for (20-44) sec.'], 
		recipe:['<i class="common">common weapon</i>','<card>The Fool</card>','<i class="rare">rare demon power</i>']},
];
const triggers = [
	{name:'Barbaric', trigger:'Charge with (100-340) Energy per Special Weapon attack'},
	{name:'Bastion', trigger:'Charge with (50-110) Energy per Deflected Attack'},
	{name:'Brute', trigger:'Charge with (0.10-0.28) Energy per 1 Damage Dealt'},
	{name:'Egotistical', trigger:'Charge with (100-460) Energy per Positive Condition Gained'},
	{name:'Fatal', trigger:'Charge with (15-51) Energy per Critical Hit'},
	{name:'Gluttonous', trigger:'Charge with (500-1100) Energy per Loot Picked Up'},
	{name:'Healer', trigger:'Charge with (3-11) Energy per ***1% Of Maximum Health*** Points of Health Restored'},
	{name:'Holy Warrior', trigger:'Charge with 200 Energy per second While Having (3-1) Positive Conditions'},
	{name:'Peasant', trigger:'Charge with (25-55) Energy per Basic Weapon attack'},
	{name:'Precarious', trigger:'Charge with 200 Energy per second While Below (40%-76%) Health'},
	{name:'Precise', trigger:'Charge with (50-110) Energy per Split-timed Attack'},
	{name:'Ruinous', trigger:'Charge with (340-340) per Overkill'},
	{name:'Sorcerous', trigger:'Charge with (200-320) Energy per Demon Power used'},
	{name:'Tinkerer', trigger:'Charge with (350-530) Energy per Consumable Used'},
];